### ISSUE TITLE
Position Issue

### ISSUE THREAD

**Issue by XinwenCheng** [gfranks/GFMinimalNotifications#7]
```xml
<item name="gf_notification_direction">top</item>
```
and
<code>setDirection(GFMinimalNotification.DIRECTION_TOP)</code>
has direction issue, only the first time notification appears at the top of window, since the second time, it always appears at the bottom.

Value of parameter named view is never changed.

**Comment by XinwenCheng** [comment]
OK, I got it.

GFMinimalNotification.make() cannot be called multiple times on a view, new ones' position will be wrong.

I'm not sure if this is an issue or rule, you can directly close this report if it's implemented by design.

Thanks!

**Comment by gfranks** [comment]
@XinwenCheng thanks for the comment. I am not entirely sure what the issue you are describing is. If you look at the sample project, you can see how applying the DIRECTION_TOP will work. If you are attempting to display a notification from the top, make sure to always set the direction to DIRECTION_TOP each time. I will close this issue for now but feel free to open a new issue or email me directly for inquiries. You will find my email within the README.
